### ISSUE TITLE
Possible to show and hide bar on demand?

### ISSUE THREAD

**Issue by kunalnagar** [dknight/jQuery-Notify-bar#6]
Is it possible to show and hide the bar on demand?

Something like:

```
var bar = $.notifyBar({
  html: 'Hello'
});
bar.show(); // show bar
bar.hide(); // hide bar
```

**Comment by dknight** [comment]
Hi, there aren't such functions. Maybe I will implement it when I have free time.
You can do something like:
    
    function showBar() {
        $.notifyBar({
            html: 'Hello'
        });
    }
    showBar();

**Comment by kunalnagar** [comment]
@dknight after going through the source, I realised that you already have functions that show and hide the bar. You can just expose them through the plugin.

```
// Show the bar
this.fn.showNB = function () { ... }

// Hide the bar
this.fn.hideNB = function () { ... }
```

**Comment by dknight** [comment]
Get a new version and try this.
var $bar = $.notifyBar({ ...your params... });

then

$bar.hideNB();

**Comment by kunalnagar** [comment]
Got it. Thanks! Closing.
