### ISSUE TITLE
Auto close even if "close" is defined

### ISSUE THREAD

**Issue by Qathom** [dknight/jQuery-Notify-bar#7]
Hello,

First of all, thank you for sharing this amazing plugin.
I think I found a (minor bug?): when the `close` option is defined, the notification does not disappear as expected. If it is a normal behavior, I suggest you to add another option in order to hide a notification automaticaly even if the close button is present.
What do you think?

Code example
```javascript
$.notifyBar({html: 'Message', delay: 2000, cssClass: 'notification success', close: 'X'})
```

My workaround:
```javascript
var notif = $.notifyBar({html: msg, delay: 2000, cssClass: 'fa-notification success', close: 'X'})
window.setTimeout(() => {
	// When hide is called, there is no animation!
	notif.hide()
}, 2000)
```

**Comment by dknight** [comment]
Hi, actually you are right.
I have added `waitingForClose` option. Thank you for your notice.

**Comment by Qathom** [comment]
Great! Thank you :)
I just tested this, it works perfectly.
